module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]

module.exports.campImages = [
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794841/YelpCamp/pars-sahin-V7uP-XzqX18-unsplash_v7cm7v.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794838/YelpCamp/daan-weijers-pSaEMIiUO84-unsplash_zddu88.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794836/YelpCamp/ihor-malytskyi-WvakV_ag-EQ-unsplash_g6dnrb.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794836/YelpCamp/jack-sloop-qelGaL2OLyE-unsplash_jznvyb.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794790/YelpCamp/eberhard-grossgasteiger-KX6ECaHP6wQ-unsplash_ebdoyo.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794789/YelpCamp/dan-stark-hEceQrBaIiE-unsplash_mjo7iw.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794784/YelpCamp/annie-spratt-OxTT6kZs_gU-unsplash_hberkj.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794784/YelpCamp/caleb-woods-j50op0lqTHM-unsplash_q0twov.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794782/YelpCamp/angela-benito-WgGJjGN4_ck-unsplash_clr5oe.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794782/YelpCamp/alex-robert-6Yu1cMQGu_E-unsplash_pbeqhc.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794780/YelpCamp/wolfgang-lutz-DnxzJlBoKlo-unsplash_ipgfqv.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794779/YelpCamp/veeterzy-sMQiL_2v4vs-unsplash_qopb59.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794777/YelpCamp/vadim-sherbakov-NQSWvyVRIJk-unsplash_mcdtso.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794775/YelpCamp/v2osk-1Z2niiBPg5A-unsplash_fg0n2f.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794772/YelpCamp/samuel-scrimshaw-DMcI0cmYJYk-unsplash_kfeczp.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794771/YelpCamp/tim-mossholder-p3kpqGBRPok-unsplash_tjlq99.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794771/YelpCamp/thomas-griesbeck-BS-Uxe8wU5Y-unsplash_ifvvrq.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794767/YelpCamp/john-towner-JgOeRuGD_Y4-unsplash_hjr16e.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794767/YelpCamp/ozark-drones-iWMksWAU0so-unsplash_veo71v.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794766/YelpCamp/mr-marco-QP1dUyQ8WsI-unsplash_ysy05s.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794765/YelpCamp/johny-goerend--RuRzumDbWQ-unsplash_kuvth0.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794760/YelpCamp/james-zwadlo-5RRseu8n_5s-unsplash_mfqia9.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794757/YelpCamp/freestocks-A4AeJIZpXAg-unsplash_wlurtk.jpg",
    "https://res.cloudinary.com/diil8j2cv/image/upload/v1606794765/YelpCamp/johny-goerend--RuRzumDbWQ-unsplash_kuvth0.jpg",
]

